@include('StaffOperator.layouts.header')
@include('StaffOperator.layouts.navbar')
@include('StaffOperator.layouts.sidebar')
@include('StaffOperator.layouts.content')
@include('StaffOperator.layouts.footer')